### ISSUE TITLE
設計主畫面、logo

### ISSUE THREAD

**Issue by xiang-921101** [xiang-921101/teamhw#15]

**Comment by yulin17-chang** [comment]
品牌 Logo 設計完成，並輸出.png檔上傳。

**Comment by yulin17-chang** [comment]
主畫面設計完成，附上畫面供參考。
<img width="721" alt="主畫面" src="https://github.com/user-attachments/assets/f58f49c2-f13a-4f3c-bff0-7238842ed7ec">

**Comment by yulin17-chang** [comment]
更新主畫面設計。![Image](https://github.com/user-attachments/assets/ea7f2e53-56d7-4620-913f-5a2db9a8d7eb)
